# ./argocd/twinx/apps/ovas/02-auth/omniverse-repo.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ngc-omniverse
  namespace: omni-streaming
spec:
  interval: 5m
  url: https://helm.ngc.nvidia.com/nvidia/omniverse
  secretRef:
    name: ngc-omni-user
