apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: primary-pool
  namespace: metallb
spec:
  addresses:
  - 10.38.38.200-10.38.38.255
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-advertisement
  namespace: metallb
spec:
  ipAddressPools:
  - primary-pool
