# 파일 경로: argocd/twinx/apps/nessie-resources/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: nessie-db-secret
  namespace: nessie-ns
type: Opaque
stringData:
  # PostgreSQL 배포 시 설정한 사용자 이름과 비밀번호
  username: "nessie_user"
  password: "V39fXVe5j8pElNIyB0z0UTfhr4hXPWE8N9wOXyBiEMbvnULuyrJGJYct5XGdNDMq"
