# Control Center UI를 외부에서 쉽게 접근할 수 있도록 LoadBalancer 타입의 서비스를 생성합니다.
apiVersion: v1
kind: Service
metadata:
  name: controlcenter-lb
  namespace: confluent
spec:
  type: LoadBalancer
  selector:
    app: controlcenter
  ports:
    - name: controlcenter-ui
      port: 9021
      targetPort: 9021
