apiVersion: platform.confluent.io/v1beta1
kind: KsqlDB
metadata:
  name: ksqldb
  namespace: confluent
spec:
  replicas: 1
  dataVolumeCapacity: 5Gi
  storageClass:
    name: rook-ceph-block-kafka
  image:
    application: confluentinc/cp-ksqldb-server:7.9.2
    init: confluentinc/confluent-init-container:2.11.2
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
