# ~/Git/TwinX/argocd/twinx
# Argo CD 관련 전역 설정
argo:
    namespace: argocd
    project: default
    server: https://kubernetes.default.svc
    sourceRepo:
        url: https://github.com/mj006648/TwinX.git
        branch: main


# 개별 애플리케이션 설정
applications:
    # 단순 yaml 파일들로 관리되는 애플리케이션
    # 첫 번째 애플리케이션
    cluster-config:
      enabled: true
      namespace: default
      syncWave: "-1"
      source:
        path: "argocd/twinx/apps/cluster-config"
    
    metallb-resources:
      enabled: true
      namespace: metallb-system
      syncWave: "1"
      source:
        path: "argocd/twinx/apps/metallb-resources"
    
    # Grafana Secret을 가장 먼저 배포
    grafana-resources:
      enabled: true
      namespace: monitoring
      syncWave: "2" # Prometheus보다 먼저 실행되어야 함
      source:
        path: "argocd/twinx/apps/grafana-resources"      

    twinx-web:
      enabled: true
      namespace: tx-service
      syncWave: "30"
      source:
        path: "argocd/twinx/apps/twinx-web"
    
    # Helm 차트로 관리되는 애플리케이션
    metallb:
        enabled: true
        namespace: metallb-system
        syncWave: "0"
        source:
            type: helm
            repoURL: https://metallb.github.io/metallb
            chart: metallb
            targetRevision: 0.15.2
            helm:
                valueFiles:
                    - "argocd/twinx/apps/metallb/values.yaml"

    # Prometheus 스택 배포
    prometheus:
      enabled: true
      namespace: monitoring
      syncWave: "3" # Secret이 준비된 후 실행
      source:
        type: helm
        repoURL: https://prometheus-community.github.io/helm-charts
        chart: prometheus
        targetRevision: 27.32.0
        helm:
          valueFiles:
            - "argocd/twinx/apps/prometheus/values.yaml"

    # Grafana 배포
    grafana:
      enabled: true
      namespace: monitoring
      syncWave: "4" # Secret과 Prometheus가 모두 준비된 후 실행
      source:
        type: helm
        repoURL: https://grafana.github.io/helm-charts
        chart: grafana
        targetRevision: 9.3.4
        helm:
          valueFiles:
            - "argocd/twinx/apps/grafana/values.yaml"
