# ~/Git/TwinX/argocd/twinx
# Argo CD 관련 전역 설정
argo:
    namespace: argocd
    project: default
    server: https://kubernetes.default.svc
    sourceRepo:
        url: https://github.com/mj006648/TwinX.git
        branch: main


# 개별 애플리케이션 설정
applications:
    # 단순 yaml 파일들로 관리되는 애플리케이션
    # 첫 번째 애플리케이션
    cluster-config:
      enabled: true
      namespace: default
      syncWave: "-1"
      source:
        path: "argocd/twinx/apps/cluster-config"
    
    metallb-resources:
      enabled: true
      namespace: metallb-system
      syncWave: "1"
      source:
        path: "argocd/twinx/apps/metallb-resources"
    
    # Grafana Secret을 가장 먼저 배포
    grafana-resources:
      enabled: true
      namespace: monitoring
      syncWave: "15" # Prometheus보다 먼저 실행되어야 함
      source:
        path: "argocd/twinx/apps/grafana-resources"      

    twinx-web:
      enabled: true
      namespace: tx-service
      syncWave: "20"
      source:
        path: "argocd/twinx/apps/twinx-web"
    
    # Helm 차트로 관리되는 애플리케이션
    metallb:
        enabled: true
        namespace: metallb-system
        syncWave: "0"
        source:
            type: helm
            repoURL: https://metallb.github.io/metallb
            chart: metallb
            targetRevision: 0.15.2
            helm:
                valueFiles:
                    - "argocd/twinx/apps/metallb/values.yaml"

    # Prometheus 스택 배포
    prometheus:
      enabled: true
      namespace: monitoring
      syncWave: "16" # Secret이 준비된 후 실행
      source:
        type: helm
        repoURL: https://prometheus-community.github.io/helm-charts
        chart: prometheus
        targetRevision: 27.32.0
        helm:
          valueFiles:
            - "argocd/twinx/apps/prometheus/values.yaml"

    # Grafana 배포
    grafana:
      enabled: true
      namespace: monitoring
      syncWave: "17" # Secret과 Prometheus가 모두 준비된 후 실행
      source:
        type: helm
        repoURL: https://grafana.github.io/helm-charts
        chart: grafana
        targetRevision: 9.3.4
        helm:
          valueFiles:
            - "argocd/twinx/apps/grafana/values.yaml"

    csi-driver-nfs:
      enabled: true
      namespace: kube-system  # 드라이버가 설치될 네임스페이스
      syncWave: "2"
      source:
        type: helm
        repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
        chart: csi-driver-nfs
        targetRevision: 4.11.0
        helm:
          valueFiles:
            - "argocd/twinx/apps/csi-driver-nfs/values.yaml"
    # Wave 1: Operator 배포 (헬름)
    rook-ceph-operator:
      enabled: true
      namespace: rook-ceph
      syncWave: "3"
      source:
        repoURL: https://charts.rook.io/release
        chart: rook-ceph
        targetRevision: v1.17.6
        helm:
          valueFiles:
            - "argocd/twinx/apps/rook-ceph-operator/values.yaml"

    # Wave 2: Ceph 클러스터 "자체"만 배포 (헬름)
    rook-ceph-cluster:
      enabled: true
      namespace: rook-ceph
      syncWave: "4"
      source:
        repoURL: https://charts.rook.io/release
        chart: rook-ceph-cluster
        targetRevision: v1.17.6
        helm:
          valueFiles:
            - "argocd/twinx/apps/rook-ceph-cluster/values.yaml"

    # Wave 3: 클러스터가 준비된 후, 스토리지 리소스와 툴박스를 배포 (YAML)
    rook-ceph-resources:
      enabled: true
      namespace: rook-ceph # 리소스들이 생성될 기본 네임스페이스
      syncWave: "5"
      source:
        path: "argocd/twinx/apps/rook-ceph-resources"
      # 동기화 옵션을 설정하여 서버 측에서 추가된 필드를 무시하도록 합니다.
      syncOptions:
        - ServerSideApply=true
