# argocd/datax/values.yaml

# Argo CD 관련 전역 설정
argo:
    namespace: tx-argocd
    project: default
    server: https://kubernetes.default.svc
    sourceRepo:
        url: https://github.com/mj006648/TwinX.git
        branch: main

# 개별 애플리케이션 설정
applications:
    # 단순 yaml 파일들로 관리되는 애플리케이션
    cluster-config:
        enabled: true
        namespace: default
        syncWave: "-1"
        source:
            path: "argocd/twinx/apps/cluster-config"
    metallb-resources:
        enabled: true
        namespace: metallb
        syncWave: "1" # metallb Helm 차트 설치가 끝난 후에 실행
        source:
            path: "argocd/twinx/apps/metallb-resources"
    # Helm 차트로 관리되는 애플리케이션
    metallb:
        enabled: true
        namespace: metallb
        syncWave: "0"
        source:
            type: helm
            repoURL: https://metallb.github.io/metallb
            chart: metallb
            targetRevision: 0.15.2
            helm:
                valueFiles:
                    - "argocd/twinx/apps/metallb/values.yaml"
