# Grafana 관리자 비밀번호를 미리 생성된 Secret에서 가져오도록 설정
admin:
  existingSecret: "grafana-admin-credentials"
  userKey: admin-user
  passwordKey: admin-password

# Grafana 설정을 저장할 영구 볼륨 설정
persistence:
  enabled: true
  type: pvc
  size: "5Gi"
  storageClassName: "nfs-dx-ssd-a"

securityContext:
  fsGroup: 1007
  runAsUser: 1007
  runAsGroup: 1007
  runAsNonRoot: true

# 외부 접속을 위한 서비스 설정
service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

# Prometheus 데이터소스 자동 연동 (이것은 남겨두는 것이 매우 편리합니다)
datasources:
  datasources.yaml:
    apiVersion: 1      # 일반 YAML 파일이 있는 경로를 지정
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
      access: proxy
      isDefault: true
