# ./argocd/twinx/apps/cluster-config/namespaces.yaml
apiVersion: v1
kind: Namespace
metadata:
    annotations:
        "argocd.argoproj.io/sync-options": "Prune=false,Delete=false"
    labels:
        kubernetes.io/metadata.name: argocd
    name: argocd
---
