# ./argocd/twinx/apps/ovas/04-app-definitions/isaac-sim-app-profile.yaml
apiVersion: omniverse.nvidia.com/v1
kind: ApplicationProfile
metadata:
  name: isaac-sim-omni-connect
spec:
  name: Isaac Sim with Omni Connection
  description: High-performance profile for Isaac Sim with pre-configured Omniverse connection.
  supportedApplications:
    - name: "isaac-sim"
      versions:
        - "*"
  chartMappings:
    container: streamingKit.image.repository
    container_version: streamingKit.image.tag
    name: streamingKit.name
  chartValues:
    global:
      imagePullSecrets:
        # nvcr.io용 시크릿과 방금 만든 개인 레지스트리용 시크릿을 모두 포함합니다.
        - name: regcred
        - name: dockerhub-cred
    streamingKit:
      image:
        # --- 중요! ---
        # 3단계에서 푸시한 내 이미지의 경로와 태그를 정확히 기입합니다.
        repository: ich6648/ovas-isaac-sim
        pullPolicy: Always
        tag: '1.0.0'

      service:
        type: "LoadBalancer"
      env:
        # 여기에 정의된 값들이 OVAS에 의해 자동으로 저수준 실행 인자로 변환되어 주입됩니다.
        - name: ACCEPT_EULA
          value: "Y"
        - name: PRIVACY_CONSENT
          value: "Y"
      resources:
        limits:
          cpu: "12"
          memory: "48Gi"
          nvidia.com/gpu: "1"
        requests:
          nvidia.com/gpu: "1"
      nodeSelector:
        NodeGroup: gpu
