apiVersion: omniverse.nvidia.com/v1
kind: ApplicationProfile
metadata:
  name: isaac-sim-5-0-official-v3
spec:
  name: "Isaac Sim 5.0 (OVAS Official Config)"
  description: "Final configuration for official Isaac Sim image with all settings in YAML."
  supportedApplications:
    - name: "isaac-sim"
      versions:
        - "5.0.0"
  chartMappings:
    container: streamingKit.image.repository
    container_version: streamingKit.image.tag
    name: streamingKit.name
  chartValues:
    global:
      imagePullSecrets:
        - name: regcred
    streamingKit:
      image:
        repository: "nvcr.io/nvidia/isaac-sim"
        pullPolicy: Always
        tag: "5.0.0"

      service:
        type: "LoadBalancer"

      env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: PRIVACY_CONSENT
          value: "Y"
        - name: OMNI_KIT_ALLOW_ROOT
          value: "1"

      resources:
        limits:
          cpu: "12"
          memory: "48Gi"
          nvidia.com/gpu: "1"
        requests:
          cpu: "12"
          memory: "48Gi"
          nvidia.com/gpu: "1"
      nodeSelector:
        NodeGroup: gpu

