apiVersion: omniverse.nvidia.com/v1
kind: ApplicationProfile
metadata:
  name: isaac-sim-5-0-custom-ich6648-v3
spec:
  name: "Isaac Sim 5.0 (Custom ich6648)"
  description: "Final configuration for official Isaac Sim image with all settings in YAML."
  supportedApplications:
    - name: "isaac-sim"
      versions:
        - "5.0.0"
  chartMappings:

    container: streamingKit.image.repository
    container_version: streamingKit.image.tag
    name: streamingKit.name

  chartValues:
    global:
      imagePullSecrets:
        - name: regcred

    streamingKit:
      image:
        repository: "docker.io/ich6648/ovas-isaac-sim"
        pullPolicy: Always
        tag: "3.0.0"

      iceServers:
        - urls:
            - "stun:stun.l.google.com:19302"
            - "turn:10.38.38.210:3478?transport=udp"
          credential: "test"
          username: "test"
          
      containerPorts:
        - name: signal
          containerPort: 49100
          protocol: TCP
        - name: webrtc
          containerPort: 47998
          protocol: UDP
        - name: ready
          containerPort: 8011
          protocol: TCP

      service:
        type: NodePort
        ports:
          - name: ready-8011
            port: 8011
            targetPort: 8011
            protocol: TCP
          - name: signal-49100
            port: 49100
            targetPort: 49100
            protocol: TCP
          - name: webrtc-udp-47998
            port: 47998
            targetPort: 47998
            protocol: UDP

      readinessProbe:
        httpGet:
          path: /v1/streaming/ready
          port: 8011
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 12

      startupProbe:
        httpGet:
          path: /v1/streaming/ready
          port: 8011
        initialDelaySeconds: 60
        periodSeconds: 10
        failureThreshold: 30

      env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: PRIVACY_CONSENT
          value: "Y"
        - name: OMNI_SERVER
          value: "omniverse://10.38.38.32"
        - name: OMNI_USER
          value: "admin"
        - name: OMNI_PASS
          value: "0070"
        - name: OMNI_KIT_ALLOW_ROOT
          value: "1"

      args:
        - "--headless"
        - "--/exts/omni.kit.livestream.app/primaryStream/streamType=webrtc"
        - "--/exts/omni.kit.livestream.app/primaryStream/allowDynamicResize=false"
        - "--/exts/omni.kit.livestream.app/primaryStream/targetFps=60"
        - "--/exts/omni.kit.livestream.app/primaryStream/signalPort=49100"
        - "--/exts/omni.kit.livestream.app/primaryStream/streamPort=47998"

      resources:
        limits:
          cpu: "12"
          memory: "48Gi"
          nvidia.com/gpu: "1"
        requests:
          cpu: "12"
          memory: "48Gi"
          nvidia.com/gpu: "1"

      nodeSelector:
        NodeGroup: gpu
