# ./argocd/twinx/apps/ovas/04-app-definitions/isaac-sim-app-ver5-0-3.yaml
apiVersion: omniverse.nvidia.com/v1
kind: ApplicationVersion
metadata:
  name: isaacsim-5.0.3
  labels:
    app: isaacsim
    applicationName: isaacsim
    version: '5.0.3'
spec:
  helm_chart: ngc-omniverse/kit-appstreaming-session
  helm_chart_version: '1.10.1'
  container: docker.io/ich6648/ovas-isaac-sim
  container_version: '5.0.3'
