# ./argocd/twinx/apps/ovas/04-app-definitions/isaac-app-ver-5-1.yaml
apiVersion: omniverse.nvidia.com/v1
kind: ApplicationVersion
metadata:
  name: isaac-sim-5.0.1
  labels:
    app: isaac-sim
    applicationName: isaac-sim
    version: '5.0.1'
spec:
  helm_chart: ngc-omniverse/kit-appstreaming-session
  helm_chart_version: '1.10.1'
  container: docker.io/ich6648/ovas-isaac-sim
  container_version: '5.0.1'
