apiVersion: omniverse.nvidia.com/v1
kind: ApplicationProfile
metadata:
  name: isaacsim-custom-profile5-0-0
spec:
  name: Isaacsim Custom Profile5-0-0
  description: Forcing execution of the dedicated streaming script for Isaac Sim 5.0.0.
  supportedApplications:
    - name: "isaacsim"
      versions: 
        - "*"
  chartMappings:
    container: streamingKit.image.repository
    container_version: streamingKit.image.tag
    name: streamingKit.name
  chartValues:
    global:
      imagePullSecrets:
        - name: changcred
        - name: regcred
    streamingKit:
      image:
        repository: docker.io/ich6648/ovas-isaac-sim
        pullPolicy: Always
        tag: '5.0.0'
      sessionId: session_id
      name: kit-app
      service:
        type: "LoadBalancer"

      resources:
        limits:
          cpu: "12"
          memory: "48Gi"
          nvidia.com/gpu: "1"
