apiVersion: omniverse.nvidia.com/v1
kind: ApplicationProfile
metadata:
  name: isaacsim-custom-profile5-0-0
spec:
  name: Isaacsim Custom Profile5-0-0
  description: Updated memory and CPU settings for Isaacsim.
  supportedApplications:
    - name: "isaacsim"
      versions: 
        - "5.0.0"
  chartMappings:
    container: streamingKit.image.repository
    container_version: streamingKit.image.tag
    name: streamingKit.name
  chartValues:
    global:
      imagePullSecrets:
        - name: changcred
        - name: regcred
    streamingKit:
      image:
        repository: docker.io/ich6648/ovas-isaac-sim
        pullPolicy: Always
        tag: '5.0.0'
      resources:
        requests:
          nvidia.com/gpu: "1"
        limits:
          cpu: "12"
          memory: "48Gi"
          nvidia.com/gpu: "1"
      # <<<--- 이 아랫부분을 추가해야 합니다 ---
      env:
        - name: ROS_DISTRO
          value: "humble"
        - name: RMW_IMPLEMENTATION
          value: "rmw_fastrtps_cpp"
        - name: LD_LIBRARY_PATH
          value: "/home/ubuntu/.local/share/ov/data/Kit/isaacsim.exp.template.full/0.1/exts/3/isaacsim.ros2.bridge-4.12.4+107.3.3.lx64/humble/lib/"
