# ./argocd/twinx/apps/ovas/04-app-definitions/isaac-app-profile-5-0-2.yaml
apiVersion: omniverse.nvidia.com/v1
kind: ApplicationProfile
metadata:
  name: isaacsim-custom-profile5-0-2
spec:
  name: Isaacsim Custom Profile5-0-2
  description: Updated memory and CPU settings for Isaacsim.
  supportedApplications:
    - name: "isaacsim"
      versions:
        - "5.0.2"
  chartMappings:
    container: streamingKit.image.repository
    container_version: streamingKit.image.tag
    name: streamingKit.name
  chartValues:
    global:
      imagePullSecrets:
        - name: changcred
        - name: regcred
    streamingKit:
      nucleusSecretRef: nucleus-auth
      image:
        repository: docker.io/ich6648/ovas-isaac-sim
        pullPolicy: Always
        tag: '5.0.2'
      service:
        type: "LoadBalancer" 
        annotations:
          metallb.universe.tf/address-pool: isaac-sim2-pool
      sessionId: session_id
      name: isaac2
      resources:
        requests:
          nvidia.com/gpu: "1"
        limits:
          cpu: "12"
          memory: "48Gi"
          nvidia.com/gpu: "1"
