apiVersion: omniverse.nvidia.com/v1
kind: ApplicationProfile
metadata:
  name: isaacsim-custom-profile4-1-1  # "default"에서 고유한 이름으로 변경
spec:
  name: Isaacsim Custom Profile4-1-1 # spec.name도 명확하게 바꿔주는 것이 좋습니다.
  description: Updated memory and CPU settings for Isaacsim.
  supportedApplications:
    - name: "isaacsim"
      versions: 
        - "4.1.1"
  chartMappings:
    container: streamingKit.image.repository
    container_version: streamingKit.image.tag
    name: streamingKit.name
  chartValues:
    global:
      imagePullSecrets:
        - name: changcred
        - name: regcred
    streamingKit:
      image:
        repository: docker.io/ich6648/ovas-isaac-sim
        pullPolicy: Always
        tag: '4.1.1'
      sessionId: session_id
      name: kit-test
      resources:
        requests:
          nvidia.com/gpu: "1"
        limits:
          cpu: "12"
          memory: "48Gi"
          nvidia.com/gpu: "1"
