# ./argocd/twinx/apps/ovas/04-app-definitions/isaac-sim-app-profile.yaml
apiVersion: omniverse.nvidia.com/v1
kind: ApplicationProfile
metadata:
  name: isaac-sim-omni-connect
spec:
  name: Isaac Sim with Omni Connection
  description: High-performance profile for Isaac Sim with pre-configured Omniverse connection.
  supportedApplications:
    - name: "isaac-sim"
      versions:
        - "*"
  chartMappings:
    container: streamingKit.image.repository
    container_version: streamingKit.image.tag
    name: streamingKit.name
  chartValues:
    global:
      imagePullSecrets:
        - name: regcred
    streamingKit:
      service:
        type: "LoadBalancer"

      # --- Docker의 "-e" (환경 변수) 부분을 여기에 반영 ---
      env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: PRIVACY_CONSENT
          value: "Y"
        - name: OMNI_SERVER
          value: "omniverse://10.38.38.32"
        - name: OMNI_USER
          value: "admin"
        - name: OMNI_PASS 
          value: "0070" 
          
      # --- Docker의 "--gpus" (리소스) 부분을 여기에 반영 ---
      resources:
        limits:
          cpu: "12" 
          memory: "48Gi" 
          # docker run 명령어에서 3개의 GPU를 요청했으므로 "3"으로 설정
          nvidia.com/gpu: "1" 
        requests:
          # 요청과 한도를 동일하게 맞추는 것이 안정적입니다.
          nvidia.com/gpu: "1"
          
      # --- Docker의 Entrypoint/CMD 부분을 여기에 반영 ---
      # 스트리밍을 위한 헤드리스 실행(no-window)이 핵심입니다.
      args:
        - --no-window
        - --exts.kit.app.streaming.enabled=true
        - --exts.kit.app.streaming.viewport.enabled=true
        - --exts.kit.app.streaming.gui.enabled=true

      nodeSelector:
        NodeGroup: gpu
