# ./argocd/twinx/apps/ovas/04-app-definitions/isaac-sim-app-profile-v3.yaml
apiVersion: omniverse.nvidia.com/v1
kind: ApplicationProfile
metadata:
  name: isaac-sim-5-0-custom-v5 # v5
spec:
  name: Isaac Sim 5.0 (Custom Livestream V4 )
  description: "Restored static streaming args to YAML 'args' section for entrypoint script."
  supportedApplications:
    - name: "isaac-sim"
      versions:
        - "5.0.0"
  chartMappings:
    container: streamingKit.image.repository
    container_version: streamingKit.image.tag
    name: streamingKit.name
  chartValues:
    global:
      imagePullSecrets:
        - name: regcred
    streamingKit:
      image:
        repository: "ttyy441/isaac-sim" # [수정] 나중에 여기 이미지 주소 수정
        pullPolicy: Always
        tag: "5.0"
      service:
        type: "LoadBalancer"
        ports:
          - name: http
            port: 8080
            targetPort: 8080
            protocol: TCP
          - name: signal
            port: 49100
            targetPort: 49100
            protocol: TCP
          - name: media
            port: 1024
            targetPort: 1024
            protocol: UDP        
      env:
        # --- entrypoint.sh가 읽을 환경 변수들 --- (여기는 기존 4.5 버전 환경변수들 추가 예정)
        - name: ACCEPT_EULA
          value: "Y"
        - name: PRIVACY_CONSENT
          value: "Y"
        - name: OMNI_SERVER
          value: "omniverse://10.38.38.32"
        - name: OMNI_USER
          value: "admin"
        - name: OMNI_PASS
          value: "0070"
        - name: OMNI_KIT_ALLOW_ROOT
          value: "1"
        - name: LIVESTREAM_STREAM_TYPE
          value: "webrtc"


      # --- [수정] entrypoint.sh의 "$@"로 전달될 필수 인자들 ---
      # https://github.com/NVIDIA-Omniverse/web-viewer-sample
      args:
        - "--headless"
        # --- 스트리밍 필수 인자들 복원 ---
        - "--/exts/omni.kit.livestream.app/primaryStream/allowDynamicResize=false"
        - "--/exts/omni.kit.livestream.app/primaryStream/targetFps=60"
        - "--/exts/omni.kit.livestream.app/primaryStream/signalPort=49100"
        - "--/exts/omni.kit.livestream.app/primaryStream/publicIp=0.0.0.0"

      resources:
        limits:
          cpu: "12"
          memory: "48Gi"
          nvidia.com/gpu: "1"
        requests:
          cpu: "12"
          memory: "48Gi"
          nvidia.com/gpu: "1"
      nodeSelector:
        NodeGroup: gpu