# ./argocd/twinx/apps/ovas/04-app-definitions/streaming-service.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: omniverse-streaming-manager-sa
  namespace: omni-streaming
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: omniverse-streaming-manager-role
  namespace: omni-streaming
rules:
# 스트리밍 매니저가 새로 생성된 스트리밍 Pod의 'Service'를 찾아 IP와 포트를 확인해야 합니다.
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
# 스트리밍 Pod 자체의 상태를 확인할 수도 있으므로 Pod 조회 권한도 부여합니다.
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: omniverse-streaming-manager-binding
  namespace: omni-streaming
subjects:
- kind: ServiceAccount
  name: omniverse-streaming-manager-sa # 위에서 만든 ServiceAccount 이름과 일치
  namespace: omni-streaming
roleRef:
  kind: Role
  name: omniverse-streaming-manager-role # 위에서 만든 Role 이름과 일치
  apiGroup: rbac.authorization.k8s.io
