# 테스트용 stun/turn 서버 배포 yaml

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coturn-config-v2
  namespace: omni-streaming
data:
  turnserver.conf: |
    # LoadBalancer Service의 ClusterIP에서 리슨
    listening-ip=0.0.0.0
    
    # LoadBalancer Service의 외부 IP를 서버가 인식하도록 함
    # [필수 수정!] 이 IP는 'coturn-lb-service'가 할당받을 IP
    external-ip=10.38.38.210
    
    # STUN/TURN 기본 포트
    listening-port=3478
    
    # 로그를 stdout으로 출력
    log-file=stdout
    
    # WebRTC 클라이언트가 사용할 realm (자동으로 external-ip를 사용)
    realm=auto
    
    # [필수 수정!] 
    # 여기에 WebRTC 인증을 위한 임의의 긴 비밀 키를 입력 (지금은 test 를 위해 평문으로 간단하게 입력함)
    static-auth-secret=test
    
    # TURN 중계(Relay)에 사용할 UDP 포트 범위 (10개로 최소화)
    min-port=49152
    max-port=49162 
    
    # 인증서가 없으므로 TLS 비활성화
    no-tls
    no-dtls
    
    # 기타 권장 설정
    no-multicast-peers
    no-cli

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coturn-deployment
  namespace: omni-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coturn
  template:
    metadata:
      labels:
        app: coturn
    spec:
      containers:
        - name: turn
          image: coturn/coturn:latest
          command: ["turnserver", "-c", "/etc/turnserver.conf"]
          ports:
            # STUN 포트
            - name: stun-udp
              containerPort: 3478
              protocol: UDP
            - name: stun-tcp
              containerPort: 3478
              protocol: TCP
            # TURN 중계 포트 범위 (컨테이너 내부)
            - name: relay-udp
              containerPort: 49152
              protocol: UDP
            - name: relay-udp-2
              containerPort: 49153
              protocol: UDP
            - name: relay-udp-3
              containerPort: 49154
              protocol: UDP
            - name: relay-udp-4
              containerPort: 49155
              protocol: UDP
            - name: relay-udp-5
              containerPort: 49156
              protocol: UDP
            - name: relay-udp-6
              containerPort: 49157
              protocol: UDP
            - name: relay-udp-7
              containerPort: 49158
              protocol: UDP
            - name: relay-udp-8
              containerPort: 49159
              protocol: UDP
            - name: relay-udp-9
              containerPort: 49160
              protocol: UDP
            - name: relay-udp-10
              containerPort: 49161
              protocol: UDP
            - name: relay-udp-11
              containerPort: 49162
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /etc/turnserver.conf
              subPath: turnserver.conf
      volumes:
        - name: config
          configMap:
            name: coturn-config-v2

---
apiVersion: v1
kind: Service
metadata:
  name: coturn-lb-service
  namespace: omni-streaming
spec:
  # [중요] LoadBalancer 타입으로 외부 IP 할당
  type: LoadBalancer
  # [필수 수정!] 위쪽 ConfigMap의 external-ip와 동일한 IP 지정
  loadBalancerIP: 10.38.38.210 
  selector:
    app: coturn
  ports:
    # STUN 포트 (TCP/UDP)
    - name: stun-udp
      port: 3478
      targetPort: 3478
      protocol: UDP
    - name: stun-tcp
      port: 3478
      targetPort: 3478
      protocol: TCP
      
    # TURN 중계 포트 (반드시 UDP)
    - name: relay-udp-0
      port: 49152
      targetPort: 49152
      protocol: UDP
    - name: relay-udp-1
      port: 49153
      targetPort: 49153
      protocol: UDP
    - name: relay-udp-2
      port: 49154
      targetPort: 49154
      protocol: UDP
    - name: relay-udp-3
      port: 49155
      targetPort: 49155
      protocol: UDP
    - name: relay-udp-4
      port: 49156
      targetPort: 49156
      protocol: UDP
    - name: relay-udp-5
      port: 49157
      targetPort: 49157
      protocol: UDP
    - name: relay-udp-6
      port: 49158
      targetPort: 49158
      protocol: UDP
    - name: relay-udp-7
      port: 49159
      targetPort: 49159
      protocol: UDP
    - name: relay-udp-8
      port: 49160
      targetPort: 49160
      protocol: UDP
    - name: relay-udp-9
      port: 49161
      targetPort: 49161
      protocol: UDP
    - name: relay-udp-10
      port: 49162
      targetPort: 49162
      protocol: UDP