# 파일 경로: argocd/twinx/apps/postgresql/values.yaml

###############################################################################
# CloudNativePG 클러스터 Helm 차트 values.yaml for ArgoCD
# 단일 인스턴스, LoadBalancer, Nessie 카탈로그용 구성
###############################################################################

#-- 클러스터의 인스턴스(Pod) 수. 'standalone'과 동일하게 1로 설정합니다.
instances: 1

#-- PostgreSQL 클러스터의 초기 설정을 담당합니다.
bootstrap:
  initdb:
    # Nessie 카탈로그용으로 자동 생성할 데이터베이스 이름
    database: nessiedb
    # 위 데이터베이스의 소유자가 될 사용자 이름
    owner: nessie_user
    # 'nessie_user'의 암호를 저장할 Kubernetes Secret을 자동으로 생성합니다.
    # 이 Secret에서 암호를 조회하여 접속에 사용합니다.
    secret:
      name: nessie-user-secret

#-- 슈퍼유저(postgres)의 암호를 저장하고 관리할 Secret의 이름입니다.
# 이 Secret 또한 CloudNativePG가 자동으로 생성하고 관리합니다.
superuserSecret:
  name: postgres-superuser-secret

#-- 데이터 영속성을 위한 스토리지 설정
storage:
  # PersistentVolumeClaim(PVC)의 크기
  size: 10Gi
  # 클러스터에 존재하는 StorageClass 이름을 정확히 지정합니다.
  storageClass: "rook-ceph-block"

#-- 서비스 외부 노출 방식 설정
# 서비스를 LoadBalancer 타입으로 설정하여 외부 IP를 할당받습니다.
service:
  type: LoadBalancer

#-- Pod의 리소스 요청량 및 최대 사용량 제한
resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

#-- 참고: CloudNativePG는 shmVolume 이나 volumePermissions 같은 설정을
#-- 자동으로 최적화하여 관리하므로 별도의 설정이 필요 없습니다.
