# 파일 경로: argocd/twinx/apps/cloudnativepg-cluster-resource/loadbalancer.yaml

apiVersion: v1
kind: Service
metadata:
  # 서비스 이름도 새로운 클러스터 이름에 맞춰 변경
  name: nessie-database-lb
  namespace: postgre
spec:
  type: LoadBalancer
  selector:
    cnpg.io/cluster: nessie-database
    cnpg.io/instanceRole: primary
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
