# 파일 경로: argocd/twinx/apps/superset/values.yaml

#==============================================================================
# 전역(Global) 설정
#==============================================================================
global:
  storageClass: "rook-ceph-block"

#==============================================================================
# Superset 웹 UI (Frontend) 설정
#==============================================================================
web:
  service:
    type: LoadBalancer
    ports:
      http: 8088
  extraEnvVars:
    - name: PYTHONPATH
      value: "/opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs"
  extraVolumes:
    - name: custom-libs
      emptyDir: {}
  extraVolumeMounts:
    - name: custom-libs
      mountPath: /opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs
  initContainers:
    - name: install-drivers
      image: docker.io/bitnami/python:3.10
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 0
      command:
        - "/bin/sh"
        - "-c"
        - |
          pip install --target=/opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs PyHive thrift-sasl psycopg2-binary trino
      volumeMounts:
        - name: custom-libs
          mountPath: /opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs

#==============================================================================
# Superset 백그라운드 워커 (Celery) 설정
#==============================================================================
worker:
  # 메모리 부족(OOMKilled) 문제 해결을 위해 리소스를 넉넉하게 설정
  resources:
    requests:
      cpu: "1"
      memory: "4Gi"
    limits:
      cpu: "2"
      memory: "8Gi"

  # 데이터베이스 드라이버 라이브러리를 추가하기 위한 설정
  extraEnvVars:
    - name: PYTHONPATH
      value: "/opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs"
  extraVolumes:
    - name: custom-libs
      emptyDir: {}
  extraVolumeMounts:
    - name: custom-libs
      mountPath: /opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs
  initContainers:
    - name: install-drivers
      image: docker.io/bitnami/python:3.10
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 0
      command:
        - "/bin/sh"
        - "-c"
        - |
          pip install --target=/opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs PyHive thrift-sasl psycopg2-binary trino
      volumeMounts:
        - name: custom-libs
          mountPath: /opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs
          
  #############################################################################
  # ★★★★★ [최종 진단] Liveness & Readiness Probe를 완전히 비활성화 ★★★★★
  # Probe 명령어 자체가 실패하는 것으로 의심되므로, 원인 진단을 위해
  # Probe 기능을 완전히 끄고 파드가 안정적으로 실행되는지 확인합니다.
  #############################################################################
  livenessProbe:
    enabled: false

  readinessProbe:
    enabled: false

#==============================================================================
# 인증 및 보안 설정
#==============================================================================
auth:
  username: "admin"
  password: "admin"
  secretKey: 'p5gXv7yB9dE3fH2jL4mN6qR8tV0wZxC3bA1sF5uI7oK+Gg=='

#==============================================================================
# 의존성 서비스 설정 (Bitnami 하위 차트)
#==============================================================================
postgresql:
  enabled: true
redis:
  enabled: true
