# 파일 경로: argocd/twinx/apps/superset/values.yaml

#==============================================================================
# 전역(Global) 설정
#==============================================================================
global:
  storageClass: "rook-ceph-block"

#==============================================================================
# Superset 웹 UI (Frontend) 설정
#==============================================================================
web:
  service:
    type: LoadBalancer
    ports:
      http: 8088
  extraEnvVars:
    - name: PYTHONPATH
      value: "/opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs"
  extraVolumes:
    - name: custom-libs
      emptyDir: {}
  extraVolumeMounts:
    - name: custom-libs
      mountPath: /opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs
  initContainers:
    - name: install-drivers
      image: docker.io/bitnami/python:3.10
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 0
      command:
        - "/bin/sh"
        - "-c"
        - |
          pip install --target=/opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs PyHive thrift-sasl psycopg2-binary trino
      volumeMounts:
        - name: custom-libs
          mountPath: /opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs

#==============================================================================
# Superset 백그라운드 워커 (Celery) 설정
#==============================================================================
worker:
  # ★★★★★ [핵심 수정] 메모리 부족(OOMKilled) 문제 해결을 위해 리소스 대폭 상향 ★★★★★
  resources:
    requests:
      cpu: "1"
      memory: "4Gi" # 요청 메모리도 넉넉하게
    limits:
      cpu: "2"
      memory: "8Gi" # 한도 메모리를 8Gi로 대폭 상향

  # 데이터베이스 드라이버 라이브러리를 추가하기 위한 설정
  extraEnvVars:
    - name: PYTHONPATH
      value: "/opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs"
  extraVolumes:
    - name: custom-libs
      emptyDir: {}
  extraVolumeMounts:
    - name: custom-libs
      mountPath: /opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs
  initContainers:
    - name: install-drivers
      image: docker.io/bitnami/python:3.10
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 0
      command:
        - "/bin/sh"
        - "-c"
        - |
          pip install --target=/opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs PyHive thrift-sasl psycopg2-binary trino
      volumeMounts:
        - name: custom-libs
          mountPath: /opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs
          
  # Probe 설정은 그대로 유지 (이미 최신 차트의 올바른 설정이 적용됨)
  livenessProbe:
    enabled: true
    initialDelaySeconds: 120 # 초기 대기 시간을 2분으로 늘려 안정성 확보
    periodSeconds: 30
    timeoutSeconds: 20
    failureThreshold: 5
    successThreshold: 1

  readinessProbe:
    enabled: true
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 20
    failureThreshold: 5
    successThreshold: 1

#==============================================================================
# 인증 및 보안 설정
#==============================================================================
auth:
  username: "admin"
  password: "admin"
  secretKey: 'p5gXv7yB9dE3fH2jL4mN6qR8tV0wZxC3bA1sF5uI7oK+Gg=='

#==============================================================================
# 의존성 서비스 설정 (Bitnami 하위 차트)
#==============================================================================
postgresql:
  enabled: true
redis:
  enabled: true
