# 파일 경로: argocd/twinx/apps/superset/values.yaml
global:
  storageClass: "rook-ceph-block"

web:
  service:
    type: LoadBalancer
    ports:
      http: 8088
  extraEnvVars:
    - name: PYTHONPATH
      value: "/opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs"
  extraVolumes:
    - name: custom-libs
      emptyDir: {}
  extraVolumeMounts:
    - name: custom-libs
      mountPath: /opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs
  initContainers:
    - name: install-drivers
      image: docker.io/bitnami/python:3.10
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 0
      command:
        - "/bin/sh"
        - "-c"
        - |
          # PyHive와 함께 thrift-sasl 패키지를 설치
          pip install --target=/opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs PyHive thrift-sasl psycopg2-binary
      volumeMounts:
        - name: custom-libs
          mountPath: /opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs

worker:
  extraEnvVars:
    - name: PYTHONPATH
      value: "/opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs"
  extraVolumes:
    - name: custom-libs
      emptyDir: {}
  extraVolumeMounts:
    - name: custom-libs
      mountPath: /opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs
  initContainers:
    - name: install-drivers
      image: docker.io/bitnami/python:3.10
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 0
      command:
        - "/bin/sh"
        - "-c"
        - |
          # Worker에도 동일하게 thrift-sasl 패키지를 설치
          pip install --target=/opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs PyHive thrift-sasl psycopg2-binary
      volumeMounts:
        - name: custom-libs
          mountPath: /opt/bitnami/superset/venv/lib/python3.10/site-packages/custom_libs

auth:
  # 사용자 이름과 비밀번호를 명시적으로 설정
  username: "admin"
  password: "admin"
  secretKey: 'p5gXv7yB9dE3fH2jL4mN6qR8tV0wZxC3bA1sF5uI7oK+Gg=='

postgresql:
  enabled: true
  ### [수정] PostgreSQL 인증 정보 추가 ###
  # 이 부분을 추가하여 데이터베이스 사용자, 암호, 데이터베이스 이름을 고정합니다.
  auth:
    username: "bn_superset"          # 로그에 나온 사용자 이름
    password: "superset-password"    # 쉬운 비밀번호 설정
    database: "bitnami_superset"     # 사용할 데이터베이스 이름
    postgresPassword: "postgres-password" # PostgreSQL 루트(admin) 비밀번호 설정

redis:
  enabled: true

